app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /v1/api
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
